LIBS += -lv4l2 \
    -lavutil \
    -lavcodec \
    -lavformat \
    -lswscale \
    -lm
HEADERS += capturethread.h \
    mainwidget.h \
    microphone.h \
    videolibi/QVideoDecoder.h \
    videolibi/QVideoEncoder.h \
    videolibi/ffmpeg.h \
    videowidget.h \
    ../sim-2.1/include/sim/analysis.h \
    ../sim-2.1/include/sim/clock.h \
    ../sim-2.1/include/sim/conditionallist.h \
    ../sim-2.1/include/sim/control.h \
    ../sim-2.1/include/sim/converter.h \
    ../sim-2.1/include/sim/coutanalysis.h \
    ../sim-2.1/include/sim/defs.h \
    ../sim-2.1/include/sim/entity.h \
    ../sim-2.1/include/sim/error.h \
    ../sim-2.1/include/sim/event.h \
    ../sim-2.1/include/sim/generator.h \
    ../sim-2.1/include/sim/handlers.h \
    ../sim-2.1/include/sim/histogram.h \
    ../sim-2.1/include/sim/hush.h \
    ../sim-2.1/include/sim/query.h \
    ../sim-2.1/include/sim/queue.h \
    ../sim-2.1/include/sim/reports.h \
    ../sim-2.1/include/sim/resource.h \
    ../sim-2.1/include/sim/scheduler.h \
    ../sim-2.1/include/sim/screen.h \
    ../sim-2.1/include/sim/sim.h \
    ../sim-2.1/include/sim/simevent.h \
    ../sim-2.1/include/sim/simulation.h \
    ../sim-2.1/include/sim/tertiarytree.h \
    ../sim-2.1/include/sim/version.h \
    ../OpenCV-2.2.0/3rdparty/include/cblas.h \
    ../OpenCV-2.2.0/3rdparty/include/clapack.h \
    ../OpenCV-2.2.0/3rdparty/include/f2c.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/avcodec.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/avfft.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/dxva2.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/opt.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/vaapi.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/vdpau.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavcodec/xvmc.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavdevice/avdevice.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavformat/avformat.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavformat/avio.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/adler32.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/attributes.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/avconfig.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/avstring.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/avutil.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/base64.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/common.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/crc.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/error.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/fifo.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/intfloat_readwrite.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/log.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/lzo.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/mathematics.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/md5.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/mem.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/pixdesc.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/pixfmt.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/rational.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libavutil/sha1.h \
    ../OpenCV-2.2.0/3rdparty/include/ffmpeg_/libswscale/swscale.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_cm.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_config.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_config2.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_debug.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_fix.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_getopt.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_icc.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_image.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_init.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_malloc.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_math.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_seq.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_stream.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_string.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_tmr.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_tvp.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_types.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jas_version.h \
    ../OpenCV-2.2.0/3rdparty/include/jasper/jasper.h \
    ../OpenCV-2.2.0/3rdparty/include/jconfig.h \
    ../OpenCV-2.2.0/3rdparty/include/jmorecfg.h \
    ../OpenCV-2.2.0/3rdparty/include/jpeglib.h \
    ../OpenCV-2.2.0/3rdparty/include/msc_inttypes.h \
    ../OpenCV-2.2.0/3rdparty/include/msc_stdint.h \
    ../OpenCV-2.2.0/3rdparty/include/png.h \
    ../OpenCV-2.2.0/3rdparty/include/pngconf.h \
    ../OpenCV-2.2.0/3rdparty/include/tiff.h \
    ../OpenCV-2.2.0/3rdparty/include/tiffconf.h \
    ../OpenCV-2.2.0/3rdparty/include/tiffio.h \
    ../OpenCV-2.2.0/3rdparty/include/tiffvers.h \
    ../OpenCV-2.2.0/3rdparty/include/videoInput.h \
    ../OpenCV-2.2.0/3rdparty/include/zconf.h \
    ../OpenCV-2.2.0/3rdparty/include/zlib.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jp2_cod.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jp2_dec.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_bs.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_cod.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_cs.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_dec.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_enc.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_fix.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_flt.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_math.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mct.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mqcod.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mqdec.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mqenc.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_qmfb.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t1cod.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t1dec.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t1enc.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t2cod.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t2dec.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t2enc.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_tagtree.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_tsfb.h \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_util.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jchuff.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdct.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdhuff.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jerror.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jinclude.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jmemsys.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jpegint.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jversion.h \
    ../OpenCV-2.2.0/3rdparty/libjpeg/transupp.h \
    ../OpenCV-2.2.0/3rdparty/libpng/png.h \
    ../OpenCV-2.2.0/3rdparty/libpng/pngpriv.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/t4.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_config.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_dir.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_fax3.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_predict.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/tiffio.hxx \
    ../OpenCV-2.2.0/3rdparty/libtiff/tiffiop.h \
    ../OpenCV-2.2.0/3rdparty/libtiff/uvcode.h \
    ../OpenCV-2.2.0/3rdparty/zlib/crc32.h \
    ../OpenCV-2.2.0/3rdparty/zlib/deflate.h \
    ../OpenCV-2.2.0/3rdparty/zlib/gzguts.h \
    ../OpenCV-2.2.0/3rdparty/zlib/inffast.h \
    ../OpenCV-2.2.0/3rdparty/zlib/inffixed.h \
    ../OpenCV-2.2.0/3rdparty/zlib/inflate.h \
    ../OpenCV-2.2.0/3rdparty/zlib/inftrees.h \
    ../OpenCV-2.2.0/3rdparty/zlib/trees.h \
    ../OpenCV-2.2.0/3rdparty/zlib/zutil.h \
    ../OpenCV-2.2.0/android/android-jni/jni/Calibration.h \
    ../OpenCV-2.2.0/android/android-jni/jni/glcamera.h \
    ../OpenCV-2.2.0/android/android-jni/jni/image_pool.h \
    ../OpenCV-2.2.0/android/android-jni/jni/yuv420sp2rgb.h \
    ../OpenCV-2.2.0/android/apps/CVCamera/jni/Processor.h \
    ../OpenCV-2.2.0/android/apps/camera_template/jni/TestBar.h \
    ../OpenCV-2.2.0/include/opencv/cv.h \
    ../OpenCV-2.2.0/include/opencv/cv.hpp \
    ../OpenCV-2.2.0/include/opencv/cvaux.h \
    ../OpenCV-2.2.0/include/opencv/cvaux.hpp \
    ../OpenCV-2.2.0/include/opencv/cvwimage.h \
    ../OpenCV-2.2.0/include/opencv/cxcore.h \
    ../OpenCV-2.2.0/include/opencv/cxcore.hpp \
    ../OpenCV-2.2.0/include/opencv/cxeigen.hpp \
    ../OpenCV-2.2.0/include/opencv/cxmisc.h \
    ../OpenCV-2.2.0/include/opencv/highgui.h \
    ../OpenCV-2.2.0/include/opencv/ml.h \
    ../OpenCV-2.2.0/include/opencv2/opencv.hpp \
    ../OpenCV-2.2.0/modules/calib3d/include/opencv2/calib3d/calib3d.hpp \
    ../OpenCV-2.2.0/modules/calib3d/src/_modelest.h \
    ../OpenCV-2.2.0/modules/calib3d/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/contrib/include/opencv2/contrib/contrib.hpp \
    ../OpenCV-2.2.0/modules/contrib/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/core.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/core_c.h \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/eigen.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/internal.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/mat.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/operations.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/types_c.h \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/version.hpp \
    ../OpenCV-2.2.0/modules/core/include/opencv2/core/wimage.hpp \
    ../OpenCV-2.2.0/modules/core/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/features2d/include/opencv2/features2d/features2d.hpp \
    ../OpenCV-2.2.0/modules/features2d/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/ffmpeg/ffopencv.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/all_indices.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/allocator.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/autotuned_index.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/composite_index.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/dist.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/flann.hpp \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/flann_base.hpp \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/general.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/ground_truth.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/hdf5.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/heap.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/index_testing.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/kdtree_index.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/kmeans_index.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/linear_index.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/logger.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/matrix.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/nn_index.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/object_factory.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/random.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/result_set.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/sampling.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/saving.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/simplex_downhill.h \
    ../OpenCV-2.2.0/modules/flann/include/opencv2/flann/timer.h \
    ../OpenCV-2.2.0/modules/flann/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/gpu/include/opencv2/gpu/devmem2d.hpp \
    ../OpenCV-2.2.0/modules/gpu/include/opencv2/gpu/gpu.hpp \
    ../OpenCV-2.2.0/modules/gpu/include/opencv2/gpu/matrix_operations.hpp \
    ../OpenCV-2.2.0/modules/gpu/include/opencv2/gpu/stream_accessor.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/border_interpolate.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/cuda_shared.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/dynamic_smem.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/limits_gpu.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/safe_call.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/saturate_cast.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/transform.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/cuda/vecmath.hpp \
    ../OpenCV-2.2.0/modules/gpu/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/haartraining/_cvcommon.h \
    ../OpenCV-2.2.0/modules/haartraining/_cvhaartraining.h \
    ../OpenCV-2.2.0/modules/haartraining/cvclassifier.h \
    ../OpenCV-2.2.0/modules/haartraining/cvhaartraining.h \
    ../OpenCV-2.2.0/modules/highgui/include/opencv2/highgui/highgui.hpp \
    ../OpenCV-2.2.0/modules/highgui/include/opencv2/highgui/highgui_c.h \
    ../OpenCV-2.2.0/modules/highgui/src/bitstrm.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_base.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_bmp.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_exr.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_imageio.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_jpeg.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_jpeg2000.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_png.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_pxm.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_sunras.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_tiff.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmts.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/gstappsink.h \
    ../OpenCV-2.2.0/modules/highgui/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/utils.hpp \
    ../OpenCV-2.2.0/modules/highgui/src/window_QT.h \
    ../OpenCV-2.2.0/modules/imgproc/include/opencv2/imgproc/imgproc.hpp \
    ../OpenCV-2.2.0/modules/imgproc/include/opencv2/imgproc/imgproc_c.h \
    ../OpenCV-2.2.0/modules/imgproc/include/opencv2/imgproc/types_c.h \
    ../OpenCV-2.2.0/modules/imgproc/src/_featuretree.h \
    ../OpenCV-2.2.0/modules/imgproc/src/_geom.h \
    ../OpenCV-2.2.0/modules/imgproc/src/_imgproc.h \
    ../OpenCV-2.2.0/modules/imgproc/src/_kdtree.hpp \
    ../OpenCV-2.2.0/modules/imgproc/src/_list.h \
    ../OpenCV-2.2.0/modules/imgproc/src/gcgraph.hpp \
    ../OpenCV-2.2.0/modules/imgproc/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/legacy/include/opencv2/legacy/blobtrack.hpp \
    ../OpenCV-2.2.0/modules/legacy/include/opencv2/legacy/compat.hpp \
    ../OpenCV-2.2.0/modules/legacy/include/opencv2/legacy/legacy.hpp \
    ../OpenCV-2.2.0/modules/legacy/include/opencv2/legacy/streams.hpp \
    ../OpenCV-2.2.0/modules/legacy/src/_facedetection.h \
    ../OpenCV-2.2.0/modules/legacy/src/_matrix.h \
    ../OpenCV-2.2.0/modules/legacy/src/_vectrack.h \
    ../OpenCV-2.2.0/modules/legacy/src/_vm.h \
    ../OpenCV-2.2.0/modules/legacy/src/face.h \
    ../OpenCV-2.2.0/modules/legacy/src/facedetection.h \
    ../OpenCV-2.2.0/modules/legacy/src/facetemplate.h \
    ../OpenCV-2.2.0/modules/legacy/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/ml/include/opencv2/ml/ml.hpp \
    ../OpenCV-2.2.0/modules/ml/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/objdetect/include/opencv2/objdetect/objdetect.hpp \
    ../OpenCV-2.2.0/modules/objdetect/src/_latentsvm.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_distancetransform.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_error.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_fft.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_matching.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_resizeimg.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_routine.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvm_types.h \
    ../OpenCV-2.2.0/modules/objdetect/src/_lsvmparser.h \
    ../OpenCV-2.2.0/modules/objdetect/src/precomp.hpp \
    ../OpenCV-2.2.0/modules/python/opencv2x.h \
    ../OpenCV-2.2.0/modules/python/opencv_extra_api.hpp \
    ../OpenCV-2.2.0/modules/traincascade/boost.h \
    ../OpenCV-2.2.0/modules/traincascade/cascadeclassifier.h \
    ../OpenCV-2.2.0/modules/traincascade/haarfeatures.h \
    ../OpenCV-2.2.0/modules/traincascade/imagestorage.h \
    ../OpenCV-2.2.0/modules/traincascade/lbpfeatures.h \
    ../OpenCV-2.2.0/modules/traincascade/traincascade_features.h \
    ../OpenCV-2.2.0/modules/video/include/opencv2/video/background_segm.hpp \
    ../OpenCV-2.2.0/modules/video/include/opencv2/video/tracking.hpp \
    ../OpenCV-2.2.0/modules/video/src/precomp.hpp \
    ../OpenCV-2.2.0/tests/cv/src/cvchessboardgenerator.h \
    ../OpenCV-2.2.0/tests/cv/src/cvtest.h \
    ../OpenCV-2.2.0/tests/cxcore/src/cxcoretest.h \
    ../OpenCV-2.2.0/tests/cxts/_cxts.h \
    ../OpenCV-2.2.0/tests/cxts/cxts.h \
    ../OpenCV-2.2.0/tests/gpu/src/gputest.hpp \
    ../OpenCV-2.2.0/tests/ml/src/mltest.h \
    capturethread.h \
    mainwidget.h \
    microphone.h \
    videolibi/QVideoDecoder.h \
    videolibi/QVideoEncoder.h \
    videolibi/ffmpeg.h \
    videowidget.h \
    ../sim-2.1/include/sim/analysis.h \
    ../sim-2.1/include/sim/clock.h \
    ../sim-2.1/include/sim/conditionallist.h \
    ../sim-2.1/include/sim/control.h \
    ../sim-2.1/include/sim/converter.h \
    ../sim-2.1/include/sim/coutanalysis.h \
    ../sim-2.1/include/sim/defs.h \
    ../sim-2.1/include/sim/entity.h \
    ../sim-2.1/include/sim/error.h \
    ../sim-2.1/include/sim/event.h \
    ../sim-2.1/include/sim/generator.h \
    ../sim-2.1/include/sim/handlers.h \
    ../sim-2.1/include/sim/histogram.h \
    ../sim-2.1/include/sim/hush.h \
    ../sim-2.1/include/sim/query.h \
    ../sim-2.1/include/sim/queue.h \
    ../sim-2.1/include/sim/reports.h \
    ../sim-2.1/include/sim/resource.h \
    ../sim-2.1/include/sim/scheduler.h \
    ../sim-2.1/include/sim/screen.h \
    ../sim-2.1/include/sim/sim.h \
    ../sim-2.1/include/sim/simevent.h \
    ../sim-2.1/include/sim/simulation.h \
    ../sim-2.1/include/sim/tertiarytree.h \
    ../sim-2.1/include/sim/version.h \
    capturethread.h \
    mainwidget.h \
    microphone.h \
    videolibi/QVideoDecoder.h \
    videolibi/QVideoEncoder.h \
    videolibi/ffmpeg.h \
    videowidget.h \
    capturethread.h \
    videowidget.h \
    mainwidget.h \
    microphone.h
SOURCES += capturethread.cpp \
    main.cpp \
    mainwidget.cpp \
    microphone.cpp \
    videolibi/QVideoEncoder.cpp \
    videowidget.cpp \
    ../sim-2.1/examples/airport-ev.c \
    ../sim-2.1/examples/airport.c \
    ../sim-2.1/examples/altbit-ev.c \
    ../sim-2.1/examples/altbit.c \
    ../sim-2.1/examples/bank-ev.c \
    ../sim-2.1/examples/bank.c \
    ../sim-2.1/examples/csma-cd.c \
    ../sim-2.1/examples/harbour-ev.c \
    ../sim-2.1/examples/harbour.c \
    ../sim-2.1/examples/job-sc.c \
    ../sim-2.1/examples/jobshop.c \
    ../sim-2.1/examples/philo-ev.c \
    ../sim-2.1/examples/philo-sc.c \
    ../sim-2.1/examples/philosopher.c \
    ../sim-2.1/examples/post-ev.c \
    ../sim-2.1/examples/post.c \
    ../sim-2.1/examples/reliability.c \
    ../sim-2.1/examples/tankstation.c \
    ../sim-2.1/hamburgershop/client-hamburgershop.c \
    ../sim-2.1/hamburgershop/server-hamburgershop.c \
    ../sim-2.1/src/analysis.c \
    ../sim-2.1/src/clock.c \
    ../sim-2.1/src/colist.c \
    ../sim-2.1/src/control.c \
    ../sim-2.1/src/coutanal.c \
    ../sim-2.1/src/entity.c \
    ../sim-2.1/src/error.c \
    ../sim-2.1/src/generate.c \
    ../sim-2.1/src/handlers.c \
    ../sim-2.1/src/histo.c \
    ../sim-2.1/src/old-queue.c \
    ../sim-2.1/src/query.c \
    ../sim-2.1/src/queue.c \
    ../sim-2.1/src/reports.c \
    ../sim-2.1/src/resource.c \
    ../sim-2.1/src/schedule.c \
    ../sim-2.1/src/screen.c \
    ../sim-2.1/src/simevent.c \
    ../sim-2.1/src/simul.c \
    ../sim-2.1/src/tytree.c \
    ../sim-2.1/tests/testdistributions.c \
    ../sim-2.1/tests/testgenerator.c \
    ../sim-2.1/tests/testqueues.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dasum.c \
    ../OpenCV-2.2.0/3rdparty/lapack/daxpy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dbdsdc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dbdsqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dcopy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ddot.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgebd2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgebrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgelq2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgelqf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgels.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgelsd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgemm.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgemv_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgeqr2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgeqrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dger_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgesdd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgesv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgetf2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgetrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgetri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dgetrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlabad.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlabrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlacpy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlae2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaebz.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed0.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed1.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed3.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed4.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed5.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed6.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed7.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed8.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaed9.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaeda.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaev2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlagtf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlagts.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaisnan.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlals0.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlalsa.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlalsd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlamch_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlamrg.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaneg.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlange.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlanst.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlansy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlapy2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlar1v.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarfb.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarfg.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarfp.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarft.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarnv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarra.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrb.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarre.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrj.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrk.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlarrv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlartg_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaruv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlas2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlascl.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd0.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd1.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd3.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd4.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd5.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd6.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd7.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasd8.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasda.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasdq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasdt.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaset.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasq1.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasq2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasq3.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasq4.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasq5.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasq6.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasr_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasrt.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlassq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasv2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlaswp.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlasyf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlatrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlauu2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dlauum.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dnrm2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorg2r.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorgbr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorgl2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorglq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorgqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorm2l.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorm2r.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dormbr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dorml2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dormlq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dormql.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dormqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dormtr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dpotf2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dpotrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dpotri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dpotrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/drot.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dscal.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dstebz.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dstein.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dstemr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsteqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsterf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dswap.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsyevr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsymv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsyr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsyr2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsyr2k.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsyrk.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsytd2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsytf2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsytrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsytrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsytri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dsytrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dtrmm.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dtrmv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dtrsm.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dtrti2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dtrtri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/dtrtrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/f77_aloc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/idamax.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ieeeck.c \
    ../OpenCV-2.2.0/3rdparty/lapack/iladlc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/iladlr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ilaenv_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ilaslc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ilaslr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/iparmq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/isamax.c \
    ../OpenCV-2.2.0/3rdparty/lapack/pow_di.c \
    ../OpenCV-2.2.0/3rdparty/lapack/pow_ii.c \
    ../OpenCV-2.2.0/3rdparty/lapack/pow_ri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/precomp.c \
    ../OpenCV-2.2.0/3rdparty/lapack/s_cat.c \
    ../OpenCV-2.2.0/3rdparty/lapack/s_cmp.c \
    ../OpenCV-2.2.0/3rdparty/lapack/s_copy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sasum.c \
    ../OpenCV-2.2.0/3rdparty/lapack/saxpy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sbdsdc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sbdsqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/scopy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sdot.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgebd2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgebrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgelq2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgelqf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgels.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgelsd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgemm.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgemv_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgeqr2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgeqrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sger_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgesdd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgesv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgetf2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgetrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgetri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sgetrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slabad.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slabrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slacpy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slae2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaebz.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed0.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed1.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed3.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed4.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed5.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed6.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed7.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed8.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaed9.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaeda.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaev2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slagtf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slagts.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaisnan.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slals0.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slalsa.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slalsd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slamch_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slamrg.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaneg.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slange.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slanst.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slansy.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slapy2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slar1v.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarfb.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarfg.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarfp.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarft.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarnv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarra.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrb.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrc.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarre.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrj.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrk.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slarrv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slartg_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaruv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slas2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slascl.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd0.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd1.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd3.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd4.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd5.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd6.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd7.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasd8.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasda.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasdq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasdt.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaset.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasq1.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasq2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasq3.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasq4.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasq5.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasq6.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasr_custom.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasrt.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slassq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slasv2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slaswp.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slatrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slauu2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/slauum.c \
    ../OpenCV-2.2.0/3rdparty/lapack/snrm2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorg2r.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorgbr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorgl2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorglq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorgqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorm2l.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorm2r.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sormbr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sorml2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sormlq.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sormql.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sormqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sormtr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/spotf2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/spotrf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/spotri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/spotrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/srot.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sscal.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sstebz.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sstein.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sstemr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssteqr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssterf.c \
    ../OpenCV-2.2.0/3rdparty/lapack/sswap.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssyevr.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssymv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssyr2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssyr2k.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssyrk.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssytd2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/ssytrd.c \
    ../OpenCV-2.2.0/3rdparty/lapack/strmm.c \
    ../OpenCV-2.2.0/3rdparty/lapack/strmv.c \
    ../OpenCV-2.2.0/3rdparty/lapack/strsm.c \
    ../OpenCV-2.2.0/3rdparty/lapack/strti2.c \
    ../OpenCV-2.2.0/3rdparty/lapack/strtri.c \
    ../OpenCV-2.2.0/3rdparty/lapack/strtrs.c \
    ../OpenCV-2.2.0/3rdparty/lapack/xerbla.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_cm.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_debug.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_getopt.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_icc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_iccdata.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_image.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_init.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_malloc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_seq.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_stream.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_string.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_tmr.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_tvp.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jas_version.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jp2_cod.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jp2_dec.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jp2_enc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_bs.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_cs.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_dec.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_enc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_math.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mct.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mqcod.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mqdec.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_mqenc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_qmfb.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t1cod.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t1dec.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t1enc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t2cod.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t2dec.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_t2enc.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_tagtree.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_tsfb.c \
    ../OpenCV-2.2.0/3rdparty/libjasper/jpc_util.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcapimin.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcapistd.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jccoefct.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jccolor.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcdctmgr.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jchuff.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcinit.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcmainct.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcmarker.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcmaster.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcomapi.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcparam.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcphuff.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcprepct.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jcsample.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jctrans.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdapimin.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdapistd.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdatadst.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdatasrc.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdcoefct.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdcolor.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jddctmgr.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdhuff.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdinput.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdmainct.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdmarker.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdmaster.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdmerge.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdphuff.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdpostct.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdsample.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jdtrans.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jerror.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jfdctflt.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jfdctfst.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jfdctint.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jidctflt.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jidctfst.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jidctint.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jidctred.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jmemansi.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jmemmgr.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jquant1.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jquant2.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/jutils.c \
    ../OpenCV-2.2.0/3rdparty/libjpeg/transupp.c \
    ../OpenCV-2.2.0/3rdparty/libpng/png.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngerror.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngget.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngmem.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngpread.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngread.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngrio.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngrtran.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngrutil.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngset.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngtest.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngtrans.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngwio.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngwrite.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngwtran.c \
    ../OpenCV-2.2.0/3rdparty/libpng/pngwutil.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_apple.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_aux.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_close.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_codec.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_color.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_compress.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_dir.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_dirinfo.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_dirread.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_dirwrite.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_dumpmode.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_error.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_extension.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_fax3.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_fax3sm.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_flush.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_getimage.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_jbig.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_jpeg.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_luv.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_lzw.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_next.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_ojpeg.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_open.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_packbits.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_pixarlog.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_predict.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_print.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_read.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_stream.cxx \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_strip.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_swab.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_thunder.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_tile.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_unix.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_version.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_warning.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_win32.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_write.c \
    ../OpenCV-2.2.0/3rdparty/libtiff/tif_zip.c \
    ../OpenCV-2.2.0/3rdparty/zlib/adler32.c \
    ../OpenCV-2.2.0/3rdparty/zlib/compress.c \
    ../OpenCV-2.2.0/3rdparty/zlib/crc32.c \
    ../OpenCV-2.2.0/3rdparty/zlib/deflate.c \
    ../OpenCV-2.2.0/3rdparty/zlib/gzclose.c \
    ../OpenCV-2.2.0/3rdparty/zlib/gzlib.c \
    ../OpenCV-2.2.0/3rdparty/zlib/gzread.c \
    ../OpenCV-2.2.0/3rdparty/zlib/gzwrite.c \
    ../OpenCV-2.2.0/3rdparty/zlib/infback.c \
    ../OpenCV-2.2.0/3rdparty/zlib/inffast.c \
    ../OpenCV-2.2.0/3rdparty/zlib/inflate.c \
    ../OpenCV-2.2.0/3rdparty/zlib/inftrees.c \
    ../OpenCV-2.2.0/3rdparty/zlib/trees.c \
    ../OpenCV-2.2.0/3rdparty/zlib/uncompr.c \
    ../OpenCV-2.2.0/3rdparty/zlib/zutil.c \
    ../OpenCV-2.2.0/android/android-jni/jni/Calibration.cpp \
    ../OpenCV-2.2.0/android/android-jni/jni/gl_code.cpp \
    ../OpenCV-2.2.0/android/android-jni/jni/image_pool.cpp \
    ../OpenCV-2.2.0/android/android-jni/jni/yuv2rgb_neon.c \
    ../OpenCV-2.2.0/android/android-jni/jni/yuv420sp2rgb.c \
    ../OpenCV-2.2.0/android/apps/CVCamera/jni/Processor.cpp \
    ../OpenCV-2.2.0/android/apps/camera_template/jni/TestBar.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/calibinit.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/calibration.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/checkchessboard.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/fundam.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/modelest.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/posit.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/stereobm.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/stereogc.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/stereosgbm.cpp \
    ../OpenCV-2.2.0/modules/calib3d/src/triangulate.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/adaptiveskindetector.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/ba.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/chamfermatching.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/fuzzymeanshifttracker.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/octree.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/quadsubpix.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/selfsimilarity.cpp \
    ../OpenCV-2.2.0/modules/contrib/src/spinimages.cpp \
    ../OpenCV-2.2.0/modules/core/src/alloc.cpp \
    ../OpenCV-2.2.0/modules/core/src/arithm.cpp \
    ../OpenCV-2.2.0/modules/core/src/array.cpp \
    ../OpenCV-2.2.0/modules/core/src/convert.cpp \
    ../OpenCV-2.2.0/modules/core/src/copy.cpp \
    ../OpenCV-2.2.0/modules/core/src/datastructs.cpp \
    ../OpenCV-2.2.0/modules/core/src/drawing.cpp \
    ../OpenCV-2.2.0/modules/core/src/dxt.cpp \
    ../OpenCV-2.2.0/modules/core/src/lapack.cpp \
    ../OpenCV-2.2.0/modules/core/src/mathfuncs.cpp \
    ../OpenCV-2.2.0/modules/core/src/matmul.cpp \
    ../OpenCV-2.2.0/modules/core/src/matop.cpp \
    ../OpenCV-2.2.0/modules/core/src/matrix.cpp \
    ../OpenCV-2.2.0/modules/core/src/out.cpp \
    ../OpenCV-2.2.0/modules/core/src/persistence.cpp \
    ../OpenCV-2.2.0/modules/core/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/core/src/rand.cpp \
    ../OpenCV-2.2.0/modules/core/src/stat.cpp \
    ../OpenCV-2.2.0/modules/core/src/system.cpp \
    ../OpenCV-2.2.0/modules/core/src/tables.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/bagofwords.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/brief.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/calonder.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/descriptors.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/detectors.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/draw.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/dynamic.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/evaluation.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/fast.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/keypoint.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/matchers.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/mser.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/oneway.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/planardetect.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/sift.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/stardetector.cpp \
    ../OpenCV-2.2.0/modules/features2d/src/surf.cpp \
    ../OpenCV-2.2.0/modules/ffmpeg/ffopencv.cpp \
    ../OpenCV-2.2.0/modules/flann/src/flann.cpp \
    ../OpenCV-2.2.0/modules/flann/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/arithm.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/beliefpropagation_gpu.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/bilateral_filter.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/color.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/constantspacebp_gpu.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/cudastream.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/error.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/filtering.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/graphcuts.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/hog.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/imgproc_gpu.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/initialization.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/matrix_operations.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/mssegmentation.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/speckle_filtering.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/split_merge.cpp \
    ../OpenCV-2.2.0/modules/gpu/src/stereobm_gpu.cpp \
    ../OpenCV-2.2.0/modules/haartraining/createsamples.cpp \
    ../OpenCV-2.2.0/modules/haartraining/cvboost.cpp \
    ../OpenCV-2.2.0/modules/haartraining/cvcommon.cpp \
    ../OpenCV-2.2.0/modules/haartraining/cvhaarclassifier.cpp \
    ../OpenCV-2.2.0/modules/haartraining/cvhaartraining.cpp \
    ../OpenCV-2.2.0/modules/haartraining/cvsamples.cpp \
    ../OpenCV-2.2.0/modules/haartraining/haartraining.cpp \
    ../OpenCV-2.2.0/modules/haartraining/performance.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/bitstrm.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_cmu.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_dc1394.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_dc1394_v2.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_dshow.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_ffmpeg.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_gstreamer.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_images.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_libv4l.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_mil.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_pvapi.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_qt.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_tyzx.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_unicap.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_v4l.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_vfw.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_w32.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/cap_xine.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_base.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_bmp.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_exr.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_imageio.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_jpeg.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_jpeg2000.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_png.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_pxm.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_sunras.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/grfmt_tiff.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/gstappsink.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/loadsave.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/utils.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/window.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/window_QT.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/window_carbon.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/window_gtk.cpp \
    ../OpenCV-2.2.0/modules/highgui/src/window_w32.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/accum.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/approx.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/canny.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/color.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/contours.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/convhull.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/corner.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/cornersubpix.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/deriv.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/distransform.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/emd.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/featureselect.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/featuretree.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/filter.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/floodfill.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/geometry.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/grabcut.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/histogram.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/hough.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/imgwarp.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/inpaint.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/kdtree.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/linefit.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/lsh.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/matchcontours.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/moments.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/morph.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/pyramids.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/pyrsegmentation.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/rotcalipers.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/samplers.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/segmentation.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/shapedescr.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/smooth.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/spilltree.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/subdivision2d.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/sumpixels.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/tables.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/templmatch.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/thresh.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/undistort.cpp \
    ../OpenCV-2.2.0/modules/imgproc/src/utils.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/3dtracker.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/auxutils.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/bgfg_estimation.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrack.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackanalysis.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackanalysishist.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackanalysisior.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackanalysistrackdist.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackgen1.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackgenyml.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackingauto.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackingcc.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackingccwithcr.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackingkalman.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackinglist.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackingmsfg.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackingmsfgs.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackpostprockalman.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackpostproclinear.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/blobtrackpostproclist.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/calcimagehomography.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/calibfilter.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/camshift.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/clique.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/compat.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/condens.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/contourtree.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/correspond.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/corrimages.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/createhandmask.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/decomppoly.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/dominants.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/dpstereo.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/eigenobjects.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/enmin.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/enteringblobdetection.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/enteringblobdetectionreal.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/epilines.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/extendededges.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/face.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/facedetection.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/facetemplate.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/findface.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/findhandregion.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/hmm.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/hmm1d.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/hmmobs.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/image.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/lcm.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/lee.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/levmar.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/levmarprojbandle.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/levmartrif.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/lines.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/lmeds.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/morphcontours.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/morphing.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/pgh.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/prewarp.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/scanlines.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/segment.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/snakes.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/subdiv2.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/testseq.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/texture.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/trifocal.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/vecfacetracking.cpp \
    ../OpenCV-2.2.0/modules/legacy/src/video.cpp \
    ../OpenCV-2.2.0/modules/ml/src/ann_mlp.cpp \
    ../OpenCV-2.2.0/modules/ml/src/boost.cpp \
    ../OpenCV-2.2.0/modules/ml/src/cnn.cpp \
    ../OpenCV-2.2.0/modules/ml/src/data.cpp \
    ../OpenCV-2.2.0/modules/ml/src/em.cpp \
    ../OpenCV-2.2.0/modules/ml/src/ertrees.cpp \
    ../OpenCV-2.2.0/modules/ml/src/estimate.cpp \
    ../OpenCV-2.2.0/modules/ml/src/gbt.cpp \
    ../OpenCV-2.2.0/modules/ml/src/inner_functions.cpp \
    ../OpenCV-2.2.0/modules/ml/src/knearest.cpp \
    ../OpenCV-2.2.0/modules/ml/src/nbayes.cpp \
    ../OpenCV-2.2.0/modules/ml/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/ml/src/rtrees.cpp \
    ../OpenCV-2.2.0/modules/ml/src/svm.cpp \
    ../OpenCV-2.2.0/modules/ml/src/testset.cpp \
    ../OpenCV-2.2.0/modules/ml/src/tree.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/cascadedetect.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/distancetransform.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/featurepyramid.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/fft.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/haar.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/hog.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/latentsvm.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/latentsvmdetector.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/lsvmparser.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/matching.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/precomp.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/resizeimg.cpp \
    ../OpenCV-2.2.0/modules/objdetect/src/routine.cpp \
    ../OpenCV-2.2.0/modules/python/cv.cpp \
    ../OpenCV-2.2.0/modules/traincascade/boost.cpp \
    ../OpenCV-2.2.0/modules/traincascade/cascadeclassifier.cpp \
    ../OpenCV-2.2.0/modules/traincascade/features.cpp \
    ../OpenCV-2.2.0/modules/traincascade/haarfeatures.cpp \
    ../OpenCV-2.2.0/modules/traincascade/imagestorage.cpp \
    ../OpenCV-2.2.0/modules/traincascade/lbpfeatures.cpp \
    ../OpenCV-2.2.0/modules/traincascade/traincascade.cpp \
    ../OpenCV-2.2.0/modules/video/src/bgfg_acmmm2003.cpp \
    ../OpenCV-2.2.0/modules/video/src/bgfg_codebook.cpp \
    ../OpenCV-2.2.0/modules/video/src/bgfg_common.cpp \
    ../OpenCV-2.2.0/modules/video/src/bgfg_gaussmix.cpp \
    ../OpenCV-2.2.0/modules/video/src/camshift.cpp \
    ../OpenCV-2.2.0/modules/video/src/kalman.cpp \
    ../OpenCV-2.2.0/modules/video/src/lkpyramid.cpp \
    ../OpenCV-2.2.0/modules/video/src/motempl.cpp \
    ../OpenCV-2.2.0/modules/video/src/optflowbm.cpp \
    ../OpenCV-2.2.0/modules/video/src/optflowgf.cpp \
    ../OpenCV-2.2.0/modules/video/src/optflowhs.cpp \
    ../OpenCV-2.2.0/modules/video/src/optflowlk.cpp \
    ../OpenCV-2.2.0/modules/video/src/precomp.cpp \
    ../OpenCV-2.2.0/samples/MacOSX/FaceTracker/FaceTracker.cpp \
    ../OpenCV-2.2.0/samples/c/adaptiveskindetector.cpp \
    ../OpenCV-2.2.0/samples/c/bgfg_codebook.cpp \
    ../OpenCV-2.2.0/samples/c/blobtrack_sample.cpp \
    ../OpenCV-2.2.0/samples/c/contours.c \
    ../OpenCV-2.2.0/samples/c/convert_cascade.c \
    ../OpenCV-2.2.0/samples/c/delaunay.c \
    ../OpenCV-2.2.0/samples/c/example_cmake/minarea.c \
    ../OpenCV-2.2.0/samples/c/facedetect.cpp \
    ../OpenCV-2.2.0/samples/c/fback_c.c \
    ../OpenCV-2.2.0/samples/c/find_obj.cpp \
    ../OpenCV-2.2.0/samples/c/find_obj_calonder.cpp \
    ../OpenCV-2.2.0/samples/c/find_obj_ferns.cpp \
    ../OpenCV-2.2.0/samples/c/latentsvmdetect.cpp \
    ../OpenCV-2.2.0/samples/c/morphology.c \
    ../OpenCV-2.2.0/samples/c/motempl.c \
    ../OpenCV-2.2.0/samples/c/mser_sample.cpp \
    ../OpenCV-2.2.0/samples/c/mushroom.cpp \
    ../OpenCV-2.2.0/samples/c/one_way_sample.cpp \
    ../OpenCV-2.2.0/samples/c/polar_transforms.c \
    ../OpenCV-2.2.0/samples/c/pyramid_segmentation.c \
    ../OpenCV-2.2.0/samples/c/tree_engine.cpp \
    ../OpenCV-2.2.0/samples/cpp/3calibration.cpp \
    ../OpenCV-2.2.0/samples/cpp/Qt_sample/main.cpp \
    ../OpenCV-2.2.0/samples/cpp/bagofwords_classification.cpp \
    ../OpenCV-2.2.0/samples/cpp/bgfg_segm.cpp \
    ../OpenCV-2.2.0/samples/cpp/brief_match_test.cpp \
    ../OpenCV-2.2.0/samples/cpp/build3dmodel.cpp \
    ../OpenCV-2.2.0/samples/cpp/calibration.cpp \
    ../OpenCV-2.2.0/samples/cpp/calibration_artificial.cpp \
    ../OpenCV-2.2.0/samples/cpp/camshiftdemo.cpp \
    ../OpenCV-2.2.0/samples/cpp/chamfer.cpp \
    ../OpenCV-2.2.0/samples/cpp/connected_components.cpp \
    ../OpenCV-2.2.0/samples/cpp/contours2.cpp \
    ../OpenCV-2.2.0/samples/cpp/convexhull.cpp \
    ../OpenCV-2.2.0/samples/cpp/cout_mat.cpp \
    ../OpenCV-2.2.0/samples/cpp/demhist.cpp \
    ../OpenCV-2.2.0/samples/cpp/descriptor_extractor_matcher.cpp \
    ../OpenCV-2.2.0/samples/cpp/dft.cpp \
    ../OpenCV-2.2.0/samples/cpp/distrans.cpp \
    ../OpenCV-2.2.0/samples/cpp/drawing.cpp \
    ../OpenCV-2.2.0/samples/cpp/edge.cpp \
    ../OpenCV-2.2.0/samples/cpp/fback.cpp \
    ../OpenCV-2.2.0/samples/cpp/ffilldemo.cpp \
    ../OpenCV-2.2.0/samples/cpp/filestorage.cpp \
    ../OpenCV-2.2.0/samples/cpp/fitellipse.cpp \
    ../OpenCV-2.2.0/samples/cpp/generic_descriptor_match.cpp \
    ../OpenCV-2.2.0/samples/cpp/grabcut.cpp \
    ../OpenCV-2.2.0/samples/cpp/houghlines.cpp \
    ../OpenCV-2.2.0/samples/cpp/image.cpp \
    ../OpenCV-2.2.0/samples/cpp/imagelist_creator.cpp \
    ../OpenCV-2.2.0/samples/cpp/inpaint.cpp \
    ../OpenCV-2.2.0/samples/cpp/kalman.cpp \
    ../OpenCV-2.2.0/samples/cpp/kmeans.cpp \
    ../OpenCV-2.2.0/samples/cpp/laplace.cpp \
    ../OpenCV-2.2.0/samples/cpp/letter_recog.cpp \
    ../OpenCV-2.2.0/samples/cpp/lkdemo.cpp \
    ../OpenCV-2.2.0/samples/cpp/matcher_simple.cpp \
    ../OpenCV-2.2.0/samples/cpp/matching_to_many_images.cpp \
    ../OpenCV-2.2.0/samples/cpp/meanshift_segmentation.cpp \
    ../OpenCV-2.2.0/samples/cpp/minarea.cpp \
    ../OpenCV-2.2.0/samples/cpp/morphology2.cpp \
    ../OpenCV-2.2.0/samples/cpp/peopledetect.cpp \
    ../OpenCV-2.2.0/samples/cpp/segment_objects.cpp \
    ../OpenCV-2.2.0/samples/cpp/select3dobj.cpp \
    ../OpenCV-2.2.0/samples/cpp/squares.cpp \
    ../OpenCV-2.2.0/samples/cpp/starter_imagelist.cpp \
    ../OpenCV-2.2.0/samples/cpp/starter_video.cpp \
    ../OpenCV-2.2.0/samples/cpp/stereo_calib.cpp \
    ../OpenCV-2.2.0/samples/cpp/stereo_match.cpp \
    ../OpenCV-2.2.0/samples/cpp/video_homography.cpp \
    ../OpenCV-2.2.0/samples/cpp/watershed.cpp \
    ../OpenCV-2.2.0/samples/gpu/hog.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aaccum.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aadaptthresh.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aapproxpoly.cpp \
    ../OpenCV-2.2.0/tests/cv/src/abundleadjustment.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acameracalibration.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acameracalibration_artificial.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acamshift.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acanny.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acascadeandhog.cpp \
    ../OpenCV-2.2.0/tests/cv/src/achesscorners.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acolor.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acomposeRT.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acondens.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acontourmoments.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acontours.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acontoursmatch.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aconvhull.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acornerssubpix.cpp \
    ../OpenCV-2.2.0/tests/cv/src/acreatecontourtree.cpp \
    ../OpenCV-2.2.0/tests/cv/src/adetectordescriptor_evaluation.cpp \
    ../OpenCV-2.2.0/tests/cv/src/adistancetransform.cpp \
    ../OpenCV-2.2.0/tests/cv/src/adrawing.cpp \
    ../OpenCV-2.2.0/tests/cv/src/adrawing_regress.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aeigenobjects.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aemd.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aestimaterigid.cpp \
    ../OpenCV-2.2.0/tests/cv/src/afeatures2d.cpp \
    ../OpenCV-2.2.0/tests/cv/src/affine3d_estimator.cpp \
    ../OpenCV-2.2.0/tests/cv/src/afilter.cpp \
    ../OpenCV-2.2.0/tests/cv/src/afloodfill.cpp \
    ../OpenCV-2.2.0/tests/cv/src/afundam.cpp \
    ../OpenCV-2.2.0/tests/cv/src/ahistograms.cpp \
    ../OpenCV-2.2.0/tests/cv/src/ahmmobs.cpp \
    ../OpenCV-2.2.0/tests/cv/src/ahoughtransform.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aimage.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aimgwarp.cpp \
    ../OpenCV-2.2.0/tests/cv/src/akalman.cpp \
    ../OpenCV-2.2.0/tests/cv/src/akmeans.cpp \
    ../OpenCV-2.2.0/tests/cv/src/amatchcontourtrees.cpp \
    ../OpenCV-2.2.0/tests/cv/src/amoments.cpp \
    ../OpenCV-2.2.0/tests/cv/src/amotiontemplates.cpp \
    ../OpenCV-2.2.0/tests/cv/src/amotseg.cpp \
    ../OpenCV-2.2.0/tests/cv/src/amser.cpp \
    ../OpenCV-2.2.0/tests/cv/src/anearestneighbors.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aoptflowhs.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aoptflowlk.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aoptflowpyrlk.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aposit.cpp \
    ../OpenCV-2.2.0/tests/cv/src/apyrsegmentation.cpp \
    ../OpenCV-2.2.0/tests/cv/src/areprojectImageTo3D.cpp \
    ../OpenCV-2.2.0/tests/cv/src/asnakes.cpp \
    ../OpenCV-2.2.0/tests/cv/src/astereocorrespondencegc.cpp \
    ../OpenCV-2.2.0/tests/cv/src/astereomatching.cpp \
    ../OpenCV-2.2.0/tests/cv/src/asubdivisions.cpp \
    ../OpenCV-2.2.0/tests/cv/src/atemplmatch.cpp \
    ../OpenCV-2.2.0/tests/cv/src/athresh.cpp \
    ../OpenCV-2.2.0/tests/cv/src/aundistort.cpp \
    ../OpenCV-2.2.0/tests/cv/src/bcameracalibration.cpp \
    ../OpenCV-2.2.0/tests/cv/src/bchesscorners.cpp \
    ../OpenCV-2.2.0/tests/cv/src/bundistort.cpp \
    ../OpenCV-2.2.0/tests/cv/src/cvchessboardgenerator.cpp \
    ../OpenCV-2.2.0/tests/cv/src/cvtest.cpp \
    ../OpenCV-2.2.0/tests/cv/src/detectors_test.cpp \
    ../OpenCV-2.2.0/tests/cv/src/fast.cpp \
    ../OpenCV-2.2.0/tests/cv/src/grabcut.cpp \
    ../OpenCV-2.2.0/tests/cv/src/highguitest.cpp \
    ../OpenCV-2.2.0/tests/cv/src/highguitest_guionly.cpp \
    ../OpenCV-2.2.0/tests/cv/src/inpaint.cpp \
    ../OpenCV-2.2.0/tests/cv/src/latentsvmdetector.cpp \
    ../OpenCV-2.2.0/tests/cv/src/operations.cpp \
    ../OpenCV-2.2.0/tests/cv/src/optflow.cpp \
    ../OpenCV-2.2.0/tests/cv/src/tabruteforcematcher.cpp \
    ../OpenCV-2.2.0/tests/cv/src/tchesscorners.cpp \
    ../OpenCV-2.2.0/tests/cv/src/tsysa.cpp \
    ../OpenCV-2.2.0/tests/cv/src/watershed.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/aarithm.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/aarray.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/adatastruct.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/adxt.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/aio.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/amath.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/apca.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/arand.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/areduce.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/asolvepoly.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/cxcoretest_main.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/matrix_operations.cpp \
    ../OpenCV-2.2.0/tests/cxcore/src/precomp.cpp \
    ../OpenCV-2.2.0/tests/cxts/cxts.cpp \
    ../OpenCV-2.2.0/tests/cxts/cxts_arrtest.cpp \
    ../OpenCV-2.2.0/tests/cxts/cxts_math.cpp \
    ../OpenCV-2.2.0/tests/cxts/precomp.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/arithm.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/bitwise_oper.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/filters.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/gputest_main.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/hog.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/imgproc_gpu.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/meanshift.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/mssegmentation.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/operator_async_call.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/operator_convert_to.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/operator_copy_to.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/operator_set_to.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/split_merge.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/stereo_bm.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/stereo_bm_async.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/stereo_bp.cpp \
    ../OpenCV-2.2.0/tests/gpu/src/stereo_csbp.cpp \
    ../OpenCV-2.2.0/tests/ml/src/aemknearestkmeans.cpp \
    ../OpenCV-2.2.0/tests/ml/src/amltests.cpp \
    ../OpenCV-2.2.0/tests/ml/src/gbttest.cpp \
    ../OpenCV-2.2.0/tests/ml/src/mltest_main.cpp \
    ../OpenCV-2.2.0/tests/ml/src/mltests.cpp \
    ../OpenCV-2.2.0/tests/ml/src/precomp.cpp \
    ../OpenCV-2.2.0/tests/ml/src/slmltests.cpp \
    capturethread.cpp \
    main.cpp \
    mainwidget.cpp \
    microphone.cpp \
    videolibi/QVideoEncoder.cpp \
    videowidget.cpp \
    ../sim-2.1/examples/airport-ev.c \
    ../sim-2.1/examples/airport.c \
    ../sim-2.1/examples/altbit-ev.c \
    ../sim-2.1/examples/altbit.c \
    ../sim-2.1/examples/bank-ev.c \
    ../sim-2.1/examples/bank.c \
    ../sim-2.1/examples/csma-cd.c \
    ../sim-2.1/examples/harbour-ev.c \
    ../sim-2.1/examples/harbour.c \
    ../sim-2.1/examples/job-sc.c \
    ../sim-2.1/examples/jobshop.c \
    ../sim-2.1/examples/philo-ev.c \
    ../sim-2.1/examples/philo-sc.c \
    ../sim-2.1/examples/philosopher.c \
    ../sim-2.1/examples/post-ev.c \
    ../sim-2.1/examples/post.c \
    ../sim-2.1/examples/reliability.c \
    ../sim-2.1/examples/tankstation.c \
    ../sim-2.1/hamburgershop/client-hamburgershop.c \
    ../sim-2.1/hamburgershop/server-hamburgershop.c \
    ../sim-2.1/src/analysis.c \
    ../sim-2.1/src/clock.c \
    ../sim-2.1/src/colist.c \
    ../sim-2.1/src/control.c \
    ../sim-2.1/src/coutanal.c \
    ../sim-2.1/src/entity.c \
    ../sim-2.1/src/error.c \
    ../sim-2.1/src/generate.c \
    ../sim-2.1/src/handlers.c \
    ../sim-2.1/src/histo.c \
    ../sim-2.1/src/old-queue.c \
    ../sim-2.1/src/query.c \
    ../sim-2.1/src/queue.c \
    ../sim-2.1/src/reports.c \
    ../sim-2.1/src/resource.c \
    ../sim-2.1/src/schedule.c \
    ../sim-2.1/src/screen.c \
    ../sim-2.1/src/simevent.c \
    ../sim-2.1/src/simul.c \
    ../sim-2.1/src/tytree.c \
    ../sim-2.1/tests/testdistributions.c \
    ../sim-2.1/tests/testgenerator.c \
    ../sim-2.1/tests/testqueues.c \
    capturethread.cpp \
    main.cpp \
    mainwidget.cpp \
    microphone.cpp \
    videolibi/QVideoEncoder.cpp \
    videowidget.cpp \
    main.cpp \
    capturethread.cpp \
    videowidget.cpp \
    mainwidget.cpp \
    microphone.cpp
LIBS += -L./ \
    -lvideolibi
DEFINES += __STDC_CONSTANT_MACROS
SUBDIRS = videolibi
INCLUDEPATH += videolibi
FORMS += mainwidget.ui \
    mainwidget.ui \
    mainwidget.ui \
    mainwidget.ui
QT += multimedia
RESOURCES = ../OpenCV-2.2.0/modules/highgui/src/window_QT.qrc
