include ../../../install.mk

NAME = hamburgershop

FILES = README *.c resource.mk client server

SRC : sh = ls *.c

HTML = ${SRC:.c=.c.html}
DOC = index.html $(HTML)

OUT= ${SRC:.c=.out}

include examples.mk
